<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CmosCpu.Core\CmosCpu.Core.csproj" />
    <ProjectReference Include="..\CmosCpu.Bus\CmosCpu.Bus.csproj" />
    <ProjectReference Include="..\CmosCpu.Memory\CmosCpu.Memory.csproj" />
    <ProjectReference Include="..\CmosCpu.Cpu\CmosCpu.Cpu.csproj" />
    <ProjectReference Include="..\CmosCpu.Devices\CmosCpu.Devices.csproj" />
    <ProjectReference Include="..\CmosCpu.Assembler\CmosCpu.Assembler.csproj" />
    <ProjectReference Include="..\CmosCpu.Runtime\CmosCpu.Runtime.csproj" />
    <ProjectReference Include="..\CmosCpu.Computer\CmosCpu.Computer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
