<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAvalonia>true</UseAvalonia>
    <RootNamespace>Symulator.Avalonia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.*" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.*" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Symulator.Application\Symulator.Application.csproj" />
  </ItemGroup>

</Project>
