<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);Kim1DeviceTests.cs;Apple1PiaTerminalTests.cs</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.9.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CmosCpu.Computer\CmosCpu.Computer.csproj" />
    <ProjectReference Include="..\..\src\CmosCpu.Core\CmosCpu.Core.csproj" />
    <ProjectReference Include="..\..\src\Symulator.Machines.Retro70\Symulator.Machines.Retro70.csproj" />
  </ItemGroup>

</Project>
